htmlCode += `<div class="carousel-item">;
            <img class="d-block w-100" src="${img1}" alt="First slide">;
            </div>;
            <div class="carousel-item">;
            <img class="d-block w-100" src="assets/images/dr_pepper.jpg" alt="Second slide">;
            </div>;
            <div class="carousel-item">;
            <img class="d-block w-100" src="assets/images/fanta.png" alt="Third slide">;
            </div>;
            <div class="carousel-item">;
            <img class="d-block w-100" src="assets/images/sprite.jpg" alt="Fourth slide">;
            </div>`;